#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use BloomAtWork\Command\QuestionStatsCommand;

$app = new Application();
$app->add(new QuestionStatsCommand());
$app -> run();
